name: Hola mundo

on:
    push:
        branches:
            - main

jobs:
    saludo:
        runs-on: ubuntu-latest
        
        steps:
            - name: Hola mundo
              run: echo "hola mundo"
        

